### ISSUE TITLE
Update library path for USGSCSM2.0.0

### ISSUE THREAD

**Issue by chkim-usgs** [USGS-Astrogeology/knoten#118]
USGSCSM 2.0.0 library installation path has change: https://github.com/DOI-USGS/usgscsm/blob/main/CMakeLists.txt#L116

An example of this change is IsisPreferences updating the plugins path: https://github.com/DOI-USGS/ISIS3/blob/dev/isis/IsisPreferences#L181

Need to update USGSCSM's library path.

**Comment by jlaura** [comment]
A change is also needed in the `__init__` where `find_library` is called. Specifically:

```bash
$ python -c 'from ctypes.util import find_library; print(find_library("usgscsm"))'
None
$ ln -s $CONDA_PREFIX/lib/csmplugins/libusgscsm.so $CONDA_PREFIX/lib/libusgscsm.so
$ python -c 'from ctypes.util import find_library; print(find_library("usgscsm"))'
/caldera/hovenweep/projects/usgs/css/astro/apps/miniforge3/envs/autocnet1.1.0/lib/libusgscsm.so
```

It looks like `find_library` does **not** search the new sub-directory for the lib and then fails to load the plugin on import. I do not see any option in [the docs](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries) to add a path hint to find library. I also do not have a non-tacky solution at this time.

This is knoten v0.2.1 and usgscsm v2.0.1.

**Comment by acpaquette** [comment]
@jlaura With the PR that went into knoten is this resolved?

**Comment by jlaura** [comment]
For mac and linux yes. I did not see a windows one land, but perhaps it did? I'm happy to close if @Kelvinrr +1s a windows update.

**Comment by Kelvinrr** [comment]
Windows was a pain to support with knoten, I would suggest people to use WSL. I'll make a README update
