### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/knoten#12]
In order to test this library, a csm is required. Right now, the swig wrapper cooks a default CSM with a number of canned values in order to test that the API is being generated correctly. We could adopt that model here. I think that that might be the safest approach, but would require moving some of the C lang compiling items into knoten making the builds slightly more complex.

Two alternatives would be to:

1. Pull the 'fake' CSM out of swig into a stand alone repo, build that a push the artifact to somewhere publicly accessible. This might be the best approach to avoid duplication.
2. Pull the usgscsm artifact in here and instantiate sensor models from that. This requires that knoten carries around ISDs, is testing using a live model, etc. I am less enamored with this approach.

Thoughts?

**Comment by jessemapel** [comment]
I think having a generic test CSM plugin broadly available is the right choice.

**Comment by jlaura** [comment]
:+1: I am going to pull the artifact out of swigcsm and push it into its own repository. If anyone has name suggestions, let me know. Then I'll get this repo (and swigcsm) pulling that artifact locally in order to do testing.

**Comment by jlaura** [comment]
Closing as testing is using a MagicMocked RasterGM model from the csmapi. So, I believe that this is a non-issue after 5 years.
