### ISSUE TITLE
create_csm fails silently

### ISSUE THREAD

**Issue by krlberry** [USGS-Astrogeology/knoten#29]
If create_csm fails to create a camera, it returns `None`. Is this what we want it to do, or should it fail with an error?

**Comment by jessemapel** [comment]
I'm not sure if it's more Pythonic to let it return None or raise an exception.

**Comment by krlberry** [comment]
@jessemapel I don't know either. I think either is fine as long as we make a decision and know what the expected way for this to fail is.

**Comment by jessemapel** [comment]
I think for right now, we accept that it simply returns None.
