### ISSUE TITLE
Installing knoten

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/knoten#87]
I followed the instructions at 

https://github.com/USGS-Astrogeology/knoten/blob/master/README.md

to install knoten, so I ran the environment.yml file. But this did not install knoten, only its dependencies. I had to do, in addition,

conda install -c usgs-astrogeology -c conda-forge knoten

to install it, which was not mentioned anywhere. Perhaps another line needs to be added to the enviornment file for knoten itself?

**Comment by jessemapel** [comment]
The environment.yml file should install the dependencies of knoten, not knoten itself. It should have another line to run the pip install via:

`python setup.py install` or `python setup.py develop`

Installing the conda version is a separate path that should completely handle everything. You should be able to just run `conda install -c usgs-astrogeology -c conda-forge knoten` and it will pull in all the dependencies.

**Comment by oleg-alexandrov** [comment]
Thank you. I hope the doc can clarify what evnironment.yml does and how to do the rest.

**Comment by oleg-alexandrov** [comment]
This was solved in https://github.com/USGS-Astrogeology/knoten/pull/89.
