### ISSUE TITLE
Updating the Dawn notebook

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/knoten#99]
The Dawn notebook at 

https://github.com/USGS-Astrogeology/knoten/blob/master/examples/dawn_fc_isis_cmp.ipynb

needs to be updated to ISIS 6, latest ALE and USGSCSM, and then the line:

usgscsm_str = ale.loads(fileName, props={'kernels': kernels}, formatter='usgscsm', verbose=False)

needs to be replaced with:

usgscsm_str = ale.loads(fileName, props={'kernels': kernels}, formatter='ale', verbose=False)

**Comment by amystamile-usgs** [comment]
PR #133 closes this issue.
